### PR TITLE
Fix import issues related to picard.

### PR DESCRIPTION
**Pull request by vsmalladi**
@williamrowell Fixes the issue that @byoo raised. Passes womtool

### CODE REVIEW

**Comment by williamrowell** [comment]
Merged.

**Comment by byoo** [comment]
@vsmalladi, I don't see this issue below addressed and it doesn't validate in my attempt. Could you check?

> Failed to import 'https://raw.githubusercontent.com/PacificBiosciences/pb-human-wgs-workflow-wdl/main/workflows/sample/sample_trio.trial.wdl' (reason 1 of 1): Failed to process workflow definition 'sample_trio' (reason 1 of 1): Failed to process declaration 'Array[IndexedData] parent2_sample_af = select_first(select_first([p2_af, p2_uf]))' (reason 1 of 1): Failed to process expression 'select_first(select_first([p2_af, p2_uf]))' (reason 1 of 1): Invalid parameter 'ArrayLiteral(Vector(IdentifierLookup(p2_af), IdentifierLookup(p2_uf)))'. Expected an array of optional values (eg 'Array[X?]') but got 'Array[Array[Array[WomCompositeType {
>  name -> String?
> datafile -> File
> indexfile -> File
> }]?]]+'
>

**Comment by vsmalladi** [comment]
@byoo when i validate locally with womtool i don't see this. Can you send me what you are running that hits this issue?

**Comment by byoo** [comment]
@vsmalladi, ah it validates with a newer womtool. My womtool was outdated. Sorry!

**Comment by cbi-star** [comment]
In pbsv.wdl file, we call: bcftools_concat_pbsv_vcf. Then we need to bgzip and tabix the output_vcf, something like this is needed:

 call common.bgzip_vcf as bcftools_concat_pbsv_vcf_bgzip {
      input :
        vcf_input = bcftools_concat_pbsv_vcf.pbsv_vcf
        pb_conda_image = pb_conda_image
    }

**Comment by cbi-star** [comment]
As we discussed last meeting, it would be better to implement hifiasm-run (de novo assembly of patient genome) in both singleton and trio cases using the original bam files (in snakemake-based code they are called ubam)

In a trio-assembly case, we may have two more siblings in one cohort, then we need to run yak against their parents only once. It may be better to call yak.yak once for all before running trio-assembly for each siblings

**Comment by byoo** [comment]
@williamrowell, @vsmalladi, @ducatiMonster916,
As an update, I ran both singleton and trio cases and this change worked mostly. It failed in the slivar task, because our firewall blocked its attempt to download from ClinVar in production environment. We are in the process of making changes in the firewall rules.
Charlie (@cbi-star) made comments on the issues he identified. In summary,
1) sample-level pbsv run doesn't compress and index the output VCF
2) hifiasm still uses aligned bam instead of uBAM
3) yak would run multiples time on parents if there are multiple children (proband and siblings).

Thank you.

**Comment by vsmalladi** [comment]
Great. Looking into the 3 comments by @cbi-star and seeing how best to address them.

**Comment by williamrowell** [comment]
> It failed in the slivar task, because our firewall blocked its attempt to download from ClinVar in production environment. We are in the process of making changes in the firewall rules.

Instead of downloading the data from clinvar, can we just cache the file?  The snakemake code was essentially caching this, but without a shared filesystem, makes more sense to provide the file as a resource rather than download it.

There are potentially a few other cases like this as well: ensembl, tandem-genotypes... maybe others?

**Comment by vsmalladi** [comment]
So do you want to include a local input rather than url?

**Comment by cbi-star** [comment]
Very nice work, Venkat!

Two points (1 & 3) are addressed. It seems that point 2 may be missed as @byoo posted above to use ubam-files as input to both sample-hifiasm and trio-hifiasm. Thanks a lot!

**Comment by vsmalladi** [comment]
@cbi-star also fixed the ubam now. So waiting on code review.

**Comment by cbi-star** [comment]
@vsmalladi I see the ubam added thru smrtcells/pbmm2.wdl. This is great. I also noticed that you indexed the ubam to produce bai-file. We may skip this step, because samtools fasta function may not need *.bai to convert *.bam to *.fasta. How about we define ubam as this:

IndexedData ubam = { "name": smrtcell_info.name, "datafile": "~{smrtcell_info.path}", "indexfile": "None" }

**Comment by vsmalladi** [comment]
@cbi-star that is great idea. Will update to not need the index.

**Comment by cbi-star** [comment]
Perfect! BTW: in hifiasm.wdl, this disk-size may NOT include movie.indexfile in its calculation since the indexfile is empty:

  Int disk_size = ceil(multiplier * (size(movie.datafile, "GB") + size(movie.indexfile, "GB"))) + 20

**Comment by williamrowell** [comment]
Because uBAMs are not sorted by position (not aligned), they cannot be indexed.  Attempting to index them results in an error from `samtools index` and an empty .bai file.

**Comment by vsmalladi** [comment]
Yep created empty bai file that should address both of these.

**Comment by cbi-star** [comment]
In the new release,   trial.wdl: 
call sample.trial.sample_trial {
    input:
    affected_person_sample_names      = smrtcells_trial.affected_person_sample_names,
    affected_person_sample            = smrtcells_trial.affected_person_ubams,
    affected_person_jellyfish_input   = smrtcells_trial.affected_person_jellyfish_count,
    unaffected_person_sample_names    = smrtcells_trial.unaffected_person_sample_names,
    unaffected_person_sample          = smrtcells_trial.unaffected_person_ubams,
    unaffected_person_jellyfish_input = smrtcells_trial.unaffected_person_jellyfish_count,

Two lines' changes as follows: #from ubams to bams
    affected_person_sample            = smrtcells_trial.affected_person_bams, 
    unaffected_person_sample          = smrtcells_trial.unaffected_person_bams,

**Comment by vsmalladi** [comment]
@cbi-star are you saying we need to change these lines. Or is this just a comment?

**Comment by cbi-star** [comment]
@vsmalladi Yes, we need to change these lines, for we only use ubam in cases of hifiasm calling (in both sample-level and trio-level), therefore we need to do one more thing, that is, to move the sample-level hifiasm calling as shown below  out of the sample.wdl namespace:

  call hifiasm.hifiasm {
    input:
      sample_name = sample_name,
      sample = sample,
      target = reference,
      reference_name = reference.name,
      pb_conda_image = pb_conda_image
  }

In other cases of calling sample.trial.sample_trial function, as I understand from Billy's snakemake-based pipeline, the input is abam, NOT ubam, so we need to change those two lines. @williamrowell

**Comment by cbi-star** [comment]
To deal with the sample-level hifiasm calling, we may write another wdl-function to call something like this:

call hifiasm.trial.hifiasm_trial {
input:
  affected_person_sample_names = smrtcells_trial.affected_person_sample_names,
  affected_person_sample = smrtcells_trial.affected_person_ubams,
  unaffected_person_sample_names = smrtcells_trial.unaffected_person_sample_names,
  unaffected_person_sample = smrtcells_trial.unaffected_person_ubams,
  reference = reference,
       pb_conda_image = pb_conda_image
}

The new workflow hifiasm_trial defined in sample/hifiasm.trial.wdl will call the sub-workflow in sample/tasks/hifiasm.wdl

**Comment by vsmalladi** [comment]
@cbi-star got it i used ubam for all downstream, but that was incorrect. Updated so that only hifiasm and the yak use the ubam version. by adding a ubam variable that gets passed. It will be to revert once the alignment is fixed.

**Pull request merged**
