### PR TITLE
Fix import and validation bugs.

### PR DESCRIPTION
**Pull request by vsmalladi**

### CODE REVIEW

**Comment by vsmalladi** [comment]
@williamrowell @ducatiMonster916 Ready for review. This should fix the import and logic.

**Comment by byoo** [comment]
@ducatiMonster916, @williamrowell I'd appreciate if you let me know when it's ready for testing. Thanks!

**Comment by williamrowell** [comment]
@byoo It was merged last night.

**Comment by byoo** [comment]
Thank you, @williamrowell I wasn't sure if it's reviewed. @ducatiMonster916, I'll pipeline test cases later today. Let me know if you have any comments.

**Comment by vsmalladi** [comment]
@byoo working on the ubam issue as well as only running yak on the parent samples

**Pull request merged**
