### PR TITLE
Missing quotes

### PR DESCRIPTION
**Pull request by vsmalladi**
Fixed missing quotes @byoo found the issue.

### CODE REVIEW

**Comment by vsmalladi** [comment]
@williamrowell sorry quick fix.

**Comment by williamrowell** [comment]
Merged @byoo

**Comment by byoo** [comment]
@vsmalladi, the test failed at the sample_trio workflow. Not understanding the error well but wonder if "None" could be the File type value. Could you help?

https://github.com/PacificBiosciences/pb-human-wgs-workflow-wdl/blob/8122e6145772d17b7fccc833dabc64e1ea389a08/workflows/sample/sample_trio.trial.wdl#L74

> Failed to evaluate 'yak_uf_output' (reason 1 of 1): Evaluating select_first([yak_uf.yak_output, [(\"None\", \"None\")]]) failed: Could not construct array of type WomMaybeEmptyArrayType(WomOptionalType(WomMaybeEmptyArrayType(WomMaybeEmptyArrayType(WomOptionalType(WomPairType(WomStringType,WomSingleFileType)))))) with this value: List(WomOptionalValue(WomMaybeEmptyArrayType(WomMaybeEmptyArrayType(WomOptionalType(WomPairType(WomStringType,WomSingleFileType)))),Some([])), WomOptionalValue(WomMaybeEmptyArrayType(WomPairType(WomStringType,WomStringType)),Some([(\"None\", \"None\")])))

**Comment by vsmalladi** [comment]
@byoo can you send me the inout structure you used for this run?

**Comment by byoo** [comment]
@vsmalladi, I just emailed you. Thanks!

**Pull request merged**
