### PR TITLE
Fix array declaration.

### PR DESCRIPTION
**Pull request by vsmalladi**

### CODE REVIEW

**Comment by vsmalladi** [comment]
@byoo and @williamrowell  this should fix the issue. It was due to a double scatter issue. Looks to be an issue in womtool that is not catching the issue: https://github.com/broadinstitute/cromwell/issues/4550

**Comment by williamrowell** [comment]
Merged @byoo

**Comment by byoo** [comment]
@vsmalladi @williamrowell @ducatiMonster916,

The test failed with the errors below. Our on-prem cluster is going away later in the month. Could we get help on the code review instead? Charlie and I are working on the issues closely to speed up the development as much as possible. We are making a good progress and planning to make a pull request soon. Thanks much for all your help.

>           "causedBy": [
>             {
>               "message": "Failed to evaluate 'yak_uf_output' (reason 1 of 1): Evaluating if defined(flatten(yak_uf.yak_output)) then yak_af.yak_output else [(\"None\", \"None\")] failed: No coercion defined from wom value(s) '[[], [], []]' of type 'Array[Array[Pair[String, File]?]]' to 'Array[Pair[String, File]]'.",
>               "causedBy": []
>             },
>             {
>               "causedBy": [],
>               "message": "Failed to evaluate 'yak_af_output' (reason 1 of 1): Evaluating if defined(flatten(yak_af.yak_output)) then yak_af.yak_output else [(\"None\", \"None\")] failed: No coercion defined from wom value(s) '[[], [], []]' of type 'Array[Array[Pair[String, File]?]]' to 'Array[Pair[String, File]]'."
>             }
>           ],

**Comment by vsmalladi** [comment]
@byoo yes we can help. This is the area of the WDL spec that doesn't really support fully the nuance that you are trying to do. with only running Yak once. Can we run only this task with the inputs that it gets to test what the issues are in this part of the pipeline?

**Pull request merged**
