### PR TITLE
fix ubam functionality

### PR DESCRIPTION
**Pull request by ducatiMonster916**
Override readgroup override declaration when input is in uBAM format. Bug reported by CMH.

### CODE REVIEW

**Review by ducatiMonster916 — COMMENTED** [review]
bug is all cleaned up in this commit.

**Comment by williamrowell** [comment]
Preferred usage is the `--sample` option instead of the `--rg` option, as used in the snakemake workflow or in [this change](https://github.com/williamrowell/bug-free-octo-engine/blob/main/workflows/smrtcells/tasks/pbmm2.wdl) (that was reverted for some reason).  Can we switch over to `--sample` to match the snakemake implementation?  This only overrides the sample name rather than overriding the entire read group.

**Comment by ducatiMonster916** [comment]
made the reversion to match snakemake- but we had previously observed issues when we leveraged FASTQ files with the --sample flag downstream when we went to merge VCFs together due to readgroup issues.

**Comment by williamrowell** [comment]
We've never encountered any issues like this.  VCFs don't store readgroup information.  Do you have an example test case with this problem?

**Comment by ducatiMonster916** [comment]
Not at the moment, I'd have to go through our previous notes to find it- quicker validation would be I re-run with the demo data over the weekend and see if I can reproduce this error. If no error arises, we can assume previous implementation error, otherwise I'll include the error message and observations in this thread.

-Roberto

------------------------------------
Roberto Lleras
he/him
Senior Scientist, Bioinformatics
Microsoft Biomedical Platforms
Mobile: 718.578.8987
***@***.******@***.***>

[Microsoft Logo]

**Pull request merged**
