### PR TITLE
Fix error in validation

### PR DESCRIPTION
**Pull request by vsmalladi**
Fix error in valdiation between [womtool 73 vs 80](https://github.com/PacificBiosciences/pb-human-wgs-workflow-wdl/pull/68#issuecomment-1274061607). @byoo

Add manifest file. Closes $66.

Also fix renaming script.

@williamrowell ready for a quick review.

### CODE REVIEW

**Review by williamrowell — APPROVED** [review]

**Comment by williamrowell** [comment]
@byoo @vsmalladi @ducatiMonster916 Merged, ready to test.

**Comment by byoo** [comment]
@vsmalladi, the test failed. It complains that ".bai" files don't exist for the uBAMs. Is it possible not to associate a uBAM with an index?

https://github.com/PacificBiosciences/pb-human-wgs-workflow-wdl/blob/7f07b8ae4bb25e850cfb31373bbe0b3f8a0a81cf/workflows/smrtcells/tasks/pbmm2.wdl#L60

**Comment by vsmalladi** [comment]
@byoo we do have a bai file that is empty.

https://github.com/PacificBiosciences/pb-human-wgs-workflow-wdl/blob/c461160efc79cecbfe14b093e65a966733f9505b/workflows/smrtcells/tasks/pbmm2.wdl#L56

Can you do an updated pull, the example you point to is an older commit?

**Comment by byoo** [comment]
@vsmalladi, sorry the test run should have used the updated code. I am confused. The pipeline is looking for bai file for the input uBAMs that doesn't exist. Do you mean that the input uBAMs should have associated empty bai file created by the pipeline?

**Comment by vsmalladi** [comment]
@byoo That is how I wrote it. Is the downstream process expecting a bai file with data? If so then we will have to index to ubam

**Comment by williamrowell** [comment]
It's not possible to `bai` index the uBAM, so processes that use uBAM input should not require an index.

**Comment by vsmalladi** [comment]
@williamrowell  agreed 

@byoo what is the actually error?

**Comment by byoo** [comment]
@vsmalladi, "Could not process output, file not found" occurred for input uBAMs. I guess uBAM is not supposed to use the IndexedData type? Below is an error from the log and The `m64225e_220818_162540.hifi_reads.bam.bai` file doesn't exist.

> java.io.FileNotFoundException: Could not process output, file not found: /p1gmcstorpacbio01/pbdata/r64225e_20220818_161406/1_A01/m64225e_220818_162540.hifi_reads.bam.bai
>         at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.$anonfun$mapOutputWomFile$1(TesAsyncBackendJobExecutionActor.scala:277)
>         at wom.values.WomSingleFile.mapFile(WomFile.scala:201)
>         at wom.values.WomSingleFile.mapFile(WomFile.scala:182)
>         at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.mapOutputWomFile(TesAsyncBackendJobExecutionActor.scala:270)
>         at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$outputValueMapper$1(StandardAsyncExecutionActor.scala:907)
>         at wom.WomFileMapper$.$anonfun$mapWomFiles$1(WomFileMapper.scala:24)
>         at scala.util.Try$.apply(Try.scala:213)
>         at wom.WomFileMapper$.mapWomFiles(WomFileMapper.scala:24)
>         at wom.WomFileMapper$.$anonfun$mapWomFiles$6(WomFileMapper.scala:39)
>         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
>         at scala.collection.immutable.Map$Map3.foreach(Map.scala:376)
>         at scala.collection.TraversableLike.map(TraversableLike.scala:286)
>         at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
>         at scala.collection.AbstractTraversable.map(Traversable.scala:108)
>         at wom.WomFileMapper$.mapWomFiles(WomFileMapper.scala:38)
>         at cromwell.backend.standard.StandardAsyncExecutionActor.outputValueMapper(StandardAsyncExecutionActor.scala:907)
>         at cromwell.backend.standard.StandardAsyncExecutionActor.outputValueMapper$(StandardAsyncExecutionActor.scala:906)
>         at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.outputValueMapper(TesAsyncBackendJobExecutionActor.scala:55)
>         at cromwell.backend.standard.StandardAsyncExecutionActor.$anonfun$evaluateOutputs$1(StandardAsyncExecutionActor.scala:929)
>         at cromwell.backend.OutputEvaluator$.$anonfun$evaluateOutputs$5(OutputEvaluator.scala:63)
>         at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:405)
>         at scala.util.Success.flatMap(Try.scala:251)
>         at cats.instances.TryInstances$$anon$1.flatMap(try.scala:37)
>         at cats.instances.TryInstances$$anon$1.flatMap(try.scala:14)
>         at cats.data.EitherT.flatMap(EitherT.scala:403)
>         at cromwell.backend.OutputEvaluator$.$anonfun$evaluateOutputs$4(OutputEvaluator.scala:62)
>         at cats.data.EitherT.$anonfun$flatMap$1(EitherT.scala:405)
>         at scala.util.Success.flatMap(Try.scala:251)
>         at cats.instances.TryInstances$$anon$1.flatMap(try.scala:37)
>         at cats.instances.TryInstances$$anon$1.flatMap(try.scala:14)
>         at cats.data.EitherT.flatMap(EitherT.scala:403)
>

**Comment by vsmalladi** [comment]
I think it needs a non empty file. Let me do some gymnastics and do a PR.

**Pull request merged**
